In [2]:

# No terminal, uma vez: python -m pip install xlrd pandas
import pandas as pd

In [3]:
path = r"H:\Python\3° Etapa\Aula_2\Tabela 1.1.1 (1).xls"

In [6]:
indicador_1 = pd.read_excel(path, engine="xls")

ValueError: Unknown engine: xls

In [7]:
indicador_1

,uf_regiao,total,total_branca,total_preta_parda,homem_branca,homem_preta_parda,mulher_branca,mulher_preta_parda
0,Brasil,16.985781,16.545930,17.333142,11.705136,11.746330,20.404106,22.037998
1,Norte,16.187037,15.925246,16.256032,11.588653,11.514646,19.295780,20.534188
2,Rondônia,17.014162,16.727733,17.101523,12.111127,12.544080,20.412887,21.061410
3,Acre,13.606903,13.806929,13.541399,10.796120,9.686983,16.130352,16.710754
4,Amazonas,16.807290,15.987545,16.995493,12.233043,12.822584,18.764969,20.716986
5,Roraima,13.639257,13.651755,13.633606,10.814803,10.476601,16.135877,16.560244
6,Pará,16.474268,16.181627,16.560239,11.524306,11.026707,19.835110,21.591144
7,Amapá,13.586656,14.389180,13.415091,11.116821,10.749444,16.648579,15.908487
8,Tocantins,15.815781,15.701788,15.768728,10.733863,11.682616,19.663713,19.629399
9,Nordeste,18.499396,18.151700,18.610911,11.723907,11.848436,22.744666,23.716716
10,Maranhão,16.669614,16.421773,16.708894,11.665173,11.437359,19.881056,20.739589
11,Piauí,17.960366,16.948094,18.231789,12.258324,11.204814,20.494063,23.695440
12,Ceará,19.499293,18.527120,19.882469,12.186936,12.821323,23.019718,24.952274
13,Rio Grande do Norte,18.307740,18.101853,18.445218,11.166909,11.086286,23.547080,24.422884
14,Paraíba,18.920816,18.887920,18.945306,12.480204,12.400831,23.642936,24.035650
15,Pernambuco,19.306249,18.950219,19.418444,12.312833,12.868821,23.357880,24.243396
16,Alagoas,20.217129,19.165111,20.560451,12.121839,13.357160,24.093655,25.856637
17,Sergipe,18.826541,17.264294,19.317934,10.830511,11.270341,21.740902,25.637681
18,Bahia,17.849776,17.538007,17.935566,10.551673,10.982808,22.572730,23.217119
19,Sudeste,17.104218,16.834863,17.397989,11.933522,12.180843,20.732969,21.990431
20,Minas Gerais,17.502141,17.179387,17.707564,11.319720,11.619120,22.186650,23.075751
21,Espírito Santo,17.111106,16.510610,17.478861,11.798571,12.017589,20.464462,22.196626
22,Rio de Janeiro,16.716263,16.097467,17.243060,12.000036,12.864896,19.203741,20.957728
23,São Paulo,17.071295,16.964437,17.255480,12.123044,12.235200,20.771186,21.767620
24,Sul,15.527769,15.570983,15.406088,11.546629,11.159487,19.012969,19.338734
25,Paraná,15.390122,15.453295,15.307289,11.240085,10.815611,18.896661,19.365380
26,Santa Catarina,16.039355,16.124417,15.616235,12.339052,11.517342,19.414764,19.646573
27,Rio Grande do Sul,15.356709,15.337269,15.448203,11.308447,11.519941,18.868230,19.107720
28,Centro-Oeste,15.000763,14.826985,15.078025,10.546799,10.332059,18.220683,19.331040
29,Mato Grosso do Sul,15.309783,14.902105,15.567204,10.446213,11.126920,18.593200,19.542761
30,Mato Grosso,14.239989,14.083513,14.270209,9.479654,9.265734,17.782825,18.695923
31,Goiás,15.186471,14.962622,15.296966,10.636424,10.531883,18.440842,19.587913
32,Distrito Federal,15.096351,15.061306,15.126295,11.377952,10.481279,17.738123,19.307332

O `.xls` do IBGE mistura **título**, cabeçalho em várias linhas e **notas no rodapé**.  
Cortamos isso e deixamos só: **nomes das colunas + números**.

Tabela 1.1.1 - Número médio de horas semanais dedicadas aos cuidados de pessoas e/ou afazeres domésticos das pessoas de 14 anos ou mais de idade, na semana de referência, por sexo e cor ou raça, segundo Grandes Regiões e Unidades da Federação - Brasil - 2022

In [8]:
# Lê sem usar a 1ª linha como nome de coluna (senão o título vira "coluna")
bruto = pd.read_excel(path, engine="xlrd", header=None)

# Linhas 0–7: título/cabeçalho  |  8–40: resultados  |  41+: fonte e notas
indicador_1 = bruto.iloc[8:41].copy()
indicador_1.columns = [
    "uf_regiao",
    "total",
    "total_branca",
    "total_preta_parda",
    "homem_branca",
    "homem_preta_parda",
    "mulher_branca",
    "mulher_preta_parda",
]
indicador_1 = indicador_1.reset_index(drop=True)

# horas são número, não texto
for col in indicador_1.columns[1:]:
    indicador_1[col] = pd.to_numeric(indicador_1[col], errors="coerce")

indicador_1

,uf_regiao,total,total_branca,total_preta_parda,homem_branca,homem_preta_parda,mulher_branca,mulher_preta_parda
0,Brasil,16.985781,16.545930,17.333142,11.705136,11.746330,20.404106,22.037998
1,Norte,16.187037,15.925246,16.256032,11.588653,11.514646,19.295780,20.534188
2,Rondônia,17.014162,16.727733,17.101523,12.111127,12.544080,20.412887,21.061410
3,Acre,13.606903,13.806929,13.541399,10.796120,9.686983,16.130352,16.710754
4,Amazonas,16.807290,15.987545,16.995493,12.233043,12.822584,18.764969,20.716986
5,Roraima,13.639257,13.651755,13.633606,10.814803,10.476601,16.135877,16.560244
6,Pará,16.474268,16.181627,16.560239,11.524306,11.026707,19.835110,21.591144
7,Amapá,13.586656,14.389180,13.415091,11.116821,10.749444,16.648579,15.908487
8,Tocantins,15.815781,15.701788,15.768728,10.733863,11.682616,19.663713,19.629399
9,Nordeste,18.499396,18.151700,18.610911,11.723907,11.848436,22.744666,23.716716
10,Maranhão,16.669614,16.421773,16.708894,11.665173,11.437359,19.881056,20.739589
11,Piauí,17.960366,16.948094,18.231789,12.258324,11.204814,20.494063,23.695440
12,Ceará,19.499293,18.527120,19.882469,12.186936,12.821323,23.019718,24.952274
13,Rio Grande do Norte,18.307740,18.101853,18.445218,11.166909,11.086286,23.547080,24.422884
14,Paraíba,18.920816,18.887920,18.945306,12.480204,12.400831,23.642936,24.035650
15,Pernambuco,19.306249,18.950219,19.418444,12.312833,12.868821,23.357880,24.243396
16,Alagoas,20.217129,19.165111,20.560451,12.121839,13.357160,24.093655,25.856637
17,Sergipe,18.826541,17.264294,19.317934,10.830511,11.270341,21.740902,25.637681
18,Bahia,17.849776,17.538007,17.935566,10.551673,10.982808,22.572730,23.217119
19,Sudeste,17.104218,16.834863,17.397989,11.933522,12.180843,20.732969,21.990431
20,Minas Gerais,17.502141,17.179387,17.707564,11.319720,11.619120,22.186650,23.075751
21,Espírito Santo,17.111106,16.510610,17.478861,11.798571,12.017589,20.464462,22.196626
22,Rio de Janeiro,16.716263,16.097467,17.243060,12.000036,12.864896,19.203741,20.957728
23,São Paulo,17.071295,16.964437,17.255480,12.123044,12.235200,20.771186,21.767620
24,Sul,15.527769,15.570983,15.406088,11.546629,11.159487,19.012969,19.338734
25,Paraná,15.390122,15.453295,15.307289,11.240085,10.815611,18.896661,19.365380
26,Santa Catarina,16.039355,16.124417,15.616235,12.339052,11.517342,19.414764,19.646573
27,Rio Grande do Sul,15.356709,15.337269,15.448203,11.308447,11.519941,18.868230,19.107720
28,Centro-Oeste,15.000763,14.826985,15.078025,10.546799,10.332059,18.220683,19.331040
29,Mato Grosso do Sul,15.309783,14.902105,15.567204,10.446213,11.126920,18.593200,19.542761
30,Mato Grosso,14.239989,14.083513,14.270209,9.479654,9.265734,17.782825,18.695923
31,Goiás,15.186471,14.962622,15.296966,10.636424,10.531883,18.440842,19.587913
32,Distrito Federal,15.096351,15.061306,15.126295,11.377952,10.481279,17.738123,19.307332

In [9]:
# Média nacional = linha Brasil (dado do IBGE), não a média das linhas da tabela
media_nacional = indicador_1.loc[indicador_1["uf_regiao"] == "Brasil", "total"].item()
media_nacional

16.985780816563242

In [10]:
media_nacional

16.985780816563242

Qual(is) estado(s) está acima da média nacional de afazeres domésticos?

In [11]:
regioes = ["Norte", "Nordeste", "Sudeste", "Sul", "Centro-Oeste"]

estados = indicador_1[~indicador_1["uf_regiao"].isin(["Brasil"] + regioes)]

acima_media = estados.loc[
    estados["total"] > media_nacional,
    ["uf_regiao", "total"],
].sort_values("total", ascending=False)

print(f"Média nacional (Brasil): {media_nacional:.2f} horas/semana")
print(f"Estados acima da média: {len(acima_media)}")
acima_media

Média nacional (Brasil): 16.99 horas/semana
Estados acima da média: 12

              uf_regiao      total
16              Alagoas  20.217129
12                Ceará  19.499293
15           Pernambuco  19.306249
14              Paraíba  18.920816
17              Sergipe  18.826541
13  Rio Grande do Norte  18.307740
11                Piauí  17.960366
18                Bahia  17.849776
20         Minas Gerais  17.502141
21       Espírito Santo  17.111106
23            São Paulo  17.071295
2              Rondônia  17.014162

Quais estados estão abaixo da média?

In [12]:
regioes = ["Norte", "Nordeste", "Sudeste", "Sul", "Centro-Oeste"]

estados = indicador_1[~indicador_1["uf_regiao"].isin(["Brasil"] + regioes)]

abaixo_media = estados.loc[
    estados["total"] < media_nacional,
    ["uf_regiao", "total"],
].sort_values("total", ascending=False)

print(f"Média nacional (Brasil): {media_nacional:.2f} horas/semana")
print(f"Estados abaixo da média: {len(abaixo_media)}")
abaixo_media

Média nacional (Brasil): 16.99 horas/semana
Estados abaixo da média: 15

             uf_regiao      total
4             Amazonas  16.807290
22      Rio de Janeiro  16.716263
10            Maranhão  16.669614
6                 Pará  16.474268
26      Santa Catarina  16.039355
8            Tocantins  15.815781
25              Paraná  15.390122
27   Rio Grande do Sul  15.356709
29  Mato Grosso do Sul  15.309783
31               Goiás  15.186471
32    Distrito Federal  15.096351
30         Mato Grosso  14.239989
5              Roraima  13.639257
3                 Acre  13.606903
7                Amapá  13.586656

Qual é o percentual de diferença no Brasil que mulheres trabalham mais que homens em casa?

In [13]:

brasil = indicador_1.loc[indicador_1["uf_regiao"] == "Brasil"].iloc[0]

homem = (brasil["homem_branca"] + brasil["homem_preta_parda"]) / 2
mulher = (brasil["mulher_branca"] + brasil["mulher_preta_parda"]) / 2

# quanto % a mais as mulheres trabalham em relação aos homens
percentual = (mulher - homem) / homem * 100

print(f"Homens (média das cores):   {homem:.2f} h/semana")
print(f"Mulheres (média das cores): {mulher:.2f} h/semana")
print(f"Mulheres trabalham {percentual:.1f}% a mais que homens em casa, no Brasil.")

# recorte por cor (a tabela traz isso de fato)
perc_branca = (brasil["mulher_branca"] / brasil["homem_branca"] - 1) * 100
perc_preta_parda = (brasil["mulher_preta_parda"] / brasil["homem_preta_parda"] - 1) * 100
print(f"Branca:        mulheres +{perc_branca:.1f}%")
print(f"Preta ou parda: mulheres +{perc_preta_parda:.1f}%")

Homens (média das cores):   11.73 h/semana
Mulheres (média das cores): 21.22 h/semana
Mulheres trabalham 81.0% a mais que homens em casa, no Brasil.
Branca:        mulheres +74.3%
Preta ou parda: mulheres +87.6%

Agora responda (Com códigos):
TODAS AS RESPOSTAS DEVEM SER EM PERCENTUAL
- Quantas horas mulheres pretas trabalham a mais que mulheres brancas em Minas Gerais?
- Quantas horas mulheres pretas trabalham a mais que homens brancos no Brasil?
- Quantas horas mulheres pretas trabalham a mais que mulheres brancas no Amapá?
- Quantas horas mulheres pretas trabalham a mais que mulheres brancas no Rio Grande do Sul?
- Quantas horas mulheres pretas trabalham a mais que mulheres brancas por região["Norte", "Nordeste", "Sudeste", "Sul", "Centro-Oeste"] ?
- Dentre os estados da região sudeste Quantas horas mulheres pretas trabalham a mais que mulheres brancas?

In [14]:
def pct_mais(a, b):
    """Retorna quanto % 'a' é maior (ou menor, se negativo) que 'b'."""
    return (a - b) / b * 100

- Quantas horas mulheres pretas trabalham a mais que mulheres brancas em Minas Gerais?

In [15]:
mg = indicador_1.loc[indicador_1["uf_regiao"] == "Minas Gerais"].iloc[0]
pct_mg = pct_mais(mg["mulher_preta_parda"], mg["mulher_branca"])
print(f"Em Minas Gerais, mulheres pretas trabalham {pct_mg:.2f}% a mais que mulheres brancas.")

Em Minas Gerais, mulheres pretas trabalham 4.01% a mais que mulheres brancas.

- Quantas horas mulheres pretas trabalham a mais que homens brancos no Brasil?

In [16]:
brasil = indicador_1.loc[indicador_1["uf_regiao"] == "Brasil"].iloc[0]
pct_brasil = pct_mais(brasil["mulher_preta_parda"], brasil["homem_branca"])
print(f"No Brasil, mulheres pretas trabalham {pct_brasil:.2f}% a mais que homens brancos.")

No Brasil, mulheres pretas trabalham 88.28% a mais que homens brancos.

- Quantas horas mulheres pretas trabalham a mais que mulheres brancas no Amapá?

In [17]:
ap = indicador_1.loc[indicador_1["uf_regiao"] == "Amapá"].iloc[0]
pct_ap = pct_mais(ap["mulher_preta_parda"], ap["mulher_branca"])
print(f"No Amapá, mulheres pretas trabalham {pct_ap:.2f}% a mais que mulheres brancas.")

No Amapá, mulheres pretas trabalham -4.45% a mais que mulheres brancas.

- Quantas horas mulheres pretas trabalham a mais que mulheres brancas no Rio Grande do Sul?

In [18]:
rs = indicador_1.loc[indicador_1["uf_regiao"] == "Rio Grande do Sul"].iloc[0]
pct_rs = pct_mais(rs["mulher_preta_parda"], rs["mulher_branca"])
print(f"No Rio Grande do Sul, mulheres pretas trabalham {pct_rs:.2f}% a mais que mulheres brancas.")

No Rio Grande do Sul, mulheres pretas trabalham 1.27% a mais que mulheres brancas.

- Quantas horas mulheres pretas trabalham a mais que mulheres brancas por região["Norte", "Nordeste", "Sudeste", "Sul", "Centro-Oeste"] ?

In [19]:
regioes = ["Norte", "Nordeste", "Sudeste", "Sul", "Centro-Oeste"]

por_regiao = indicador_1[indicador_1["uf_regiao"].isin(regioes)].copy()
por_regiao["pct_preta_a_mais"] = pct_mais(
    por_regiao["mulher_preta_parda"], por_regiao["mulher_branca"]
)

por_regiao[["uf_regiao", "pct_preta_a_mais"]]

       uf_regiao  pct_preta_a_mais
1          Norte          6.418024
9       Nordeste          4.273749
19       Sudeste          6.065037
24           Sul          1.713384
28  Centro-Oeste          6.093938

- Dentre os estados da região sudeste Quantas horas mulheres pretas trabalham a mais que mulheres brancas?

In [20]:
estados_sudeste = ["Minas Gerais", "Espírito Santo", "Rio de Janeiro", "São Paulo"]

sudeste = indicador_1[indicador_1["uf_regiao"].isin(estados_sudeste)].copy()
sudeste["pct_preta_a_mais"] = pct_mais(
    sudeste["mulher_preta_parda"], sudeste["mulher_branca"]
)

sudeste[["uf_regiao", "pct_preta_a_mais"]].sort_values(
    "pct_preta_a_mais", ascending=False
)

         uf_regiao  pct_preta_a_mais
22  Rio de Janeiro          9.133569
21  Espírito Santo          8.464253
23       São Paulo          4.797194
20    Minas Gerais          4.007371